name: Feature CI

on:
  push:
    branches-ignore: ['main']
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          # List: https://github.com/conan-io/conan-docker-tools
          - gcc10
          - gcc5
          - clang10
          - clang40
        sharedlibs: [OFF, ON]

    runs-on: ubuntu-latest
    container:
      image: conanio/${{matrix.image}}
      options: --user root

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=${{matrix.sharedlibs}}
    - name: Build
      working-directory: build/
      run: cmake --build . --config Debug
    - name: Test
      working-directory: build/
      run: ctest -C Debug --output-on-failure

  macos:
    strategy:
      fail-fast: false
      matrix:
        xcode: ['11', '13']
        sharedlibs: [OFF, ON]

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{matrix.xcode}}
    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DBUILD_SHARED_LIBS=${{matrix.sharedlibs}}
    - name: Build
      working-directory: build/
      run: cmake --build .
    - name: Test
      working-directory: build/
      run: ctest --output-on-failure

  windows:
    strategy:
      fail-fast: false
      matrix:
        sharedlibs: [OFF, ON]

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Configure
      shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G"Visual Studio 16 2019" -DBUILD_SHARED_LIBS=${{matrix.sharedlibs}}
    - name: Build
      working-directory: build/
      run: cmake --build . --config Debug
    - name: Test
      working-directory: build/
      run: ctest -C Debug --output-on-failure

