name: Main CI

on:
  push:
    branches: [main]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          # List: https://github.com/conan-io/conan-docker-tools
          - gcc10
          - gcc9
          - gcc8
          - gcc7
          - gcc6
          - gcc5
          - clang10
          - clang9
          - clang8
          - clang7
          - clang60
          - clang50
          - clang40
        build_type: [Debug, Release]
        sharedlibs: [OFF, ON]

    runs-on: ubuntu-latest
    container:
      image: conanio/${{matrix.image}}
      options: --user root

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_SHARED_LIBS=${{matrix.sharedlibs}}
    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}
    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure

  macos:
    strategy:
      fail-fast: false
      matrix:
        xcode:
            - '11'
            - '12'
            - '13'
        sharedlibs: [OFF, ON]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{matrix.xcode}}
    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DBUILD_SHARED_LIBS=${{matrix.sharedlibs}}
    - name: Build
      working-directory: build/
      run: cmake --build .
    - name: Test
      working-directory: build/
      run: ctest --output-on-failure

  windows:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        sharedlibs: [OFF, ON]

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Configure
      shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G"Visual Studio 16 2019" -DBUILD_SHARED_LIBS=${{matrix.sharedlibs}}
    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}
    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure

